### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by TheBalkanDev** [aventius-software/BlazorGE#1]

**Comment by aventius-software** [comment]
Sort of ;-)

Although I've not done anything on this for a while due to other work we're doing. However, I do plan to revisit this when I've got some time as we (me and my small team of devs) would like to make some simple web games eventually using it. We all kind of prefer the coding library style of game creation like the old days (hence the influence of monogame) as opposed to the big engine style (nothing against that method though). Although it definitely needs some improvement and could do with upgrading to .NET 6.
